"""initial schema

Revision ID: 7062cd9cb800
Revises: 
Create Date: 2026-07-16 13:23:59.304344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7062cd9cb800'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=True),
    sa.Column('target', sa.String(length=80), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailbox_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configured', sa.Boolean(), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_new_messages', sa.Integer(), nullable=True),
    sa.Column('total_synced', sa.Integer(), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('inbox_folder', sa.String(length=120), nullable=True),
    sa.Column('quarantine_folder', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('false_positive_rate', sa.Float(), nullable=True),
    sa.Column('false_negative_rate', sa.Float(), nullable=True),
    sa.Column('n_train', sa.Integer(), nullable=True),
    sa.Column('n_test', sa.Integer(), nullable=True),
    sa.Column('n_feedback_folded_in', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('scans',
    sa.Column('scan_id', sa.String(length=20), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_purged', sa.Boolean(), nullable=True),
    sa.Column('classification', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('findings_json', sa.Text(), nullable=True),
    sa.Column('highlights_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_feedback', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scan_timestamp', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(length=10), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('mailbox_uid', sa.String(length=50), nullable=True),
    sa.Column('mailbox_message_id', sa.String(length=255), nullable=True),
    sa.Column('mailbox_action', sa.String(length=20), nullable=True),
    sa.Column('mailbox_action_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_index(op.f('ix_scans_mailbox_uid'), 'scans', ['mailbox_uid'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=20), nullable=False),
    sa.Column('original_label', sa.String(length=20), nullable=True),
    sa.Column('corrected_label', sa.String(length=20), nullable=True),
    sa.Column('submitted_by', sa.String(length=80), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('used_in_retrain', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('users')
    op.drop_index(op.f('ix_scans_mailbox_uid'), table_name='scans')
    op.drop_table('scans')
    op.drop_table('model_versions')
    op.drop_table('mailbox_status')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
